#!/usr/bin/env bash

HOSTNAME=$(hostname)

mkdir -p "/mnt/backup/${HOSTNAME}"
rsync -auvh --delete --progress /etc/ "/mnt/backup/${HOSTNAME}/etc"
rsync -auvh --delete --progress /opt/ "/mnt/backup/${HOSTNAME}/opt"
rsync -auvh --delete --progress --exclude=/run/ --exclude=/lock/ /var/ "/mnt/backup/${HOSTNAME}/var"
rsync -auvh --delete --progress /home/ "/mnt/backup/${HOSTNAME}/home"
